services:
  - type: web
    name: orientiq-website
    runtime: python
    buildCommand: python -m pip install -r requirements.txt
    startCommand: python manage.py migrate && python manage.py ensure_superadmin && gunicorn orentiq.wsgi:application