# Generated by Django 5.0.1 on 2026-08-10 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactinquiry_industry_portfolioproject_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('booking_type', models.CharField(choices=[('flight', 'Flight'), ('hotel', 'Hotel'), ('activity', 'Activity'), ('multi', 'Multi-Item')], default='flight', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('flight', 'Flight'), ('hotel', 'Hotel'), ('activity', 'Activity'), ('multi', 'Multi-Item')], default='flight', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('route_or_destination', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('departure_time', models.CharField(blank=True, max_length=10)),
                ('arrival_time', models.CharField(blank=True, max_length=10)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('stops', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cabin_class', models.CharField(blank=True, max_length=50)),
                ('room_type', models.CharField(blank=True, max_length=120)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('cancellation_policy', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('meeting_point', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Snapshot of the original normalized search result.')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.booking')),
            ],
            options={
                'verbose_name': 'Booking Item',
                'verbose_name_plural': 'Booking Items',
            },
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unspecified', 'Prefer Not To Say')], max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('traveler_type', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child'), ('infant', 'Infant'), ('guest', 'Guest')], default='adult', max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelers', to='core.booking')),
            ],
            options={
                'verbose_name': 'Traveler',
                'verbose_name_plural': 'Travelers',
            },
        ),
    ]
