# Generated by Django 5.0.1 on 2026-08-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_booking_bookingitem_traveler'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingitem',
            name='selection_key',
            field=models.CharField(blank=True, db_index=True, help_text="Deterministic hash of the user's inventory selection, used to prevent duplicate confirmation.", max_length=64),
        ),
    ]
