# Generated by Django 5.0.1 on 2026-08-11 05:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bookingitem_selection_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', '-created_at'], name='booking_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', '-created_at'], name='booking_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingitem',
            index=models.Index(fields=['booking', 'item_type'], name='booking_item_type_idx'),
        ),
        migrations.AddIndex(
            model_name='traveler',
            index=models.Index(fields=['booking', 'traveler_type'], name='traveler_booking_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('subtotal__gte', 0)), name='booking_subtotal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('taxes__gte', 0)), name='booking_taxes_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(check=models.Q(('total__gte', 0)), name='booking_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='bookingitem',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='booking_item_price_nonnegative'),
        ),
    ]
