# Generated by Django 5.0.1 on 2026-08-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_booking_database_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='company_name',
            field=models.CharField(default='ORENTIQ', max_length=120),
        ),
    ]
