"""Static content data for the ORENTIQ public website."""

SERVICES = [
    {
        "slug": "ai-automation",
        "name": "AI & Automation",
        "tagline": "Intelligent systems that work for you",
        "short": "Intelligent AI systems and automation designed around your business workflows.",
        "icon": "ai",
        "features": [
            "Custom AI solutions",
            "Intelligent workflow automation",
            "AI-powered document processing",
            "Predictive analytics",
            "Natural language solutions",
            "AI assistants and knowledge systems",
        ],
        "problems": [
            "Manual workflows consuming valuable time",
            "Data trapped across documents and systems",
            "Slow or inconsistent decision-making",
            "Customer support bottlenecks",
        ],
        "tech": ["Python", "OpenAI", "PyTorch", "TensorFlow", "LangChain", "PostgreSQL"],
        "benefits": [
            "Reduce repetitive operational work",
            "Accelerate decision-making with useful insights",
            "Improve consistency across workflows",
            "Scale processes more efficiently",
        ],
        "use_cases": [
            "Automated document processing & extraction",
            "AI-powered customer support assistants",
            "Predictive maintenance for equipment",
            "Intelligent sales & demand forecasting",
        ],
        "process": [
            {"number": "01", "title": "Discovery", "description": "Understand your workflows, data, goals, and opportunities for AI and automation."},
            {"number": "02", "title": "Strategy", "description": "Define the AI approach, architecture, integrations, and implementation roadmap."},
            {"number": "03", "title": "Design", "description": "Design the user experience, automation flows, and system interactions."},
            {"number": "04", "title": "Development", "description": "Build, integrate, test, and refine the solution in measurable increments."},
            {"number": "05", "title": "Launch", "description": "Deploy the solution and validate it in the real operating environment."},
            {"number": "06", "title": "Growth", "description": "Monitor performance, improve workflows, and expand capabilities over time."},
        ],
        "faqs": [
            {
                "q": "How long does an AI project take?",
                "a": "Timelines depend on the solution scope, data availability, and integration complexity. A focused proof-of-concept can typically move in 4–8 weeks, while production platforms often span 3–6 months.",
            },
            {
                "q": "Do we need existing data for AI?",
                "a": "We can work with whatever data you have available. Our team helps structure, clean, and prepare data as part of the discovery and strategy phases.",
            },
        ],
    },
    {
        "slug": "web-development",
        "name": "Web Development",
        "tagline": "Premium web platforms built to scale",
        "short": "High-performance web platforms built for usability, scalability, and long-term growth.",
        "icon": "web",
        "features": [
            "Custom web applications",
            "Business and enterprise platforms",
            "SaaS products",
            "E-commerce platforms",
            "Progressive web experiences",
            "API-driven web systems",
        ],
        "problems": [
            "Outdated websites limiting growth",
            "Slow experiences affecting engagement",
            "Platforms that cannot scale with demand",
            "Poor mobile usability",
        ],
        "tech": ["Django", "Python", "PostgreSQL", "HTML5", "CSS3", "JavaScript"],
        "benefits": [
            "Fast, responsive user experiences",
            "Search-friendly and accessible architecture",
            "Mobile-first experience",
            "Maintainable and scalable codebase",
        ],
        "use_cases": [
            "Enterprise web platforms & portals",
            "High-conversion e-commerce stores",
            "SaaS dashboards & admin panels",
            "Marketing sites & brand experiences",
        ],
        "process": [
            {"number": "01", "title": "Discovery", "description": "Understand your audience, business goals, competitive landscape, and technical requirements."},
            {"number": "02", "title": "Strategy", "description": "Define the platform architecture, roadmap, integrations, and measurable success criteria."},
            {"number": "03", "title": "Design", "description": "Create premium, user-centered interfaces and interactions optimized for your audience."},
            {"number": "04", "title": "Development", "description": "Build clean, performant code with responsive design and thorough testing."},
            {"number": "05", "title": "Launch", "description": "Deploy with SEO setup, analytics, and monitoring for ongoing visibility."},
            {"number": "06", "title": "Growth", "description": "Optimize performance, iterate based on user data, and scale as demand grows."},
        ],
        "faqs": [
            {
                "q": "What technologies do you use?",
                "a": "We build primarily with Django and Python on the backend, paired with clean HTML5, CSS3, and vanilla JavaScript on the frontend. This approach keeps applications fast, maintainable, and focused on user experience.",
            },
            {
                "q": "Can you redesign an existing site?",
                "a": "Yes. We regularly modernize legacy websites into fast, accessible, premium experiences while preserving SEO value and maintaining existing content.",
            },
        ],
    },
    {
        "slug": "mobile-development",
        "name": "Mobile Development",
        "tagline": "Native-quality mobile experiences",
        "short": "Mobile experiences designed for performance, usability, and seamless everyday use.",
        "icon": "mobile",
        "features": [
            "iOS applications",
            "Android applications",
            "Cross-platform applications",
            "Mobile UI/UX",
            "API and backend integration",
            "App deployment and maintenance",
        ],
        "problems": [
            "No effective mobile experience",
            "Poor app usability and performance",
            "Separate codebases increasing maintenance effort",
            "Difficulty turning mobile users into customers",
        ],
        "tech": ["Flutter", "React Native", "Swift", "Kotlin", "Firebase", "REST APIs"],
        "benefits": [
            "Intuitive mobile experiences",
            "Strong performance across supported devices",
            "Efficient cross-platform development when appropriate",
            "Maintainable applications with ongoing support",
        ],
        "use_cases": [
            "Customer-facing mobile apps",
            "Field & staff productivity apps",
            "Mobile-first e-commerce",
            "IoT companion apps",
        ],
        "process": [
            {"number": "01", "title": "Discovery", "description": "Understand your mobile strategy, target audience, platform priorities, and core functionality."},
            {"number": "02", "title": "Strategy", "description": "Define technical approach, native vs. cross-platform decision, integrations, and roadmap."},
            {"number": "03", "title": "Design", "description": "Design mobile-first interfaces optimized for touch, screens, and offline scenarios."},
            {"number": "04", "title": "Development", "description": "Build, test across devices, and implement backend integrations with performance focus."},
            {"number": "05", "title": "Launch", "description": "Deploy to app stores, configure analytics, and establish distribution and feedback channels."},
            {"number": "06", "title": "Growth", "description": "Monitor user feedback, optimize performance, add features, and maintain platform compatibility."},
        ],
        "faqs": [
            {
                "q": "Do you build for both iOS and Android?",
                "a": "Yes. We typically recommend cross-platform frameworks like Flutter for cost efficiency when appropriate, or native development when specific platform performance is critical. The choice depends on your product requirements.",
            },
            {
                "q": "How long does an app take?",
                "a": "Timelines depend on app complexity, feature scope, and testing requirements. An MVP can typically move faster, while full-featured production apps require more time for quality assurance and platform-specific optimization.",
            },
        ],
    },
    {
        "slug": "software-development",
        "name": "Software Development",
        "tagline": "Custom software for complex problems",
        "short": "Custom software engineered around your workflows, integrations, and operational needs.",
        "icon": "software",
        "features": [
            "Enterprise software",
            "Custom CRM and ERP systems",
            "Internal business tools",
            "Dashboards and operational systems",
            "API development and integrations",
            "Legacy system modernization",
        ],
        "problems": [
            "Off-the-shelf software not fitting the workflow",
            "Fragmented business systems",
            "Manual data entry and operational processes",
            "Legacy technology slowing growth",
        ],
        "tech": ["Python", "Django", "PostgreSQL", "Redis", "Docker", "REST / GraphQL"],
        "benefits": [
            "Software aligned with business processes",
            "Centralized and reliable business data",
            "Integration with existing systems",
            "Maintainable and documented architecture",
        ],
        "use_cases": [
            "Custom ERP / CRM platforms",
            "Operations management systems",
            "Data management & reporting tools",
            "API & microservice backbones",
        ],
        "process": [
            {"number": "01", "title": "Discovery", "description": "Understand your business processes, existing systems, pain points, and operational requirements."},
            {"number": "02", "title": "Strategy", "description": "Define the software architecture, integrations, data model, and implementation approach."},
            {"number": "03", "title": "Design", "description": "Design user workflows, dashboards, and system interfaces for your operational team."},
            {"number": "04", "title": "Development", "description": "Build, integrate with existing systems, and test across your operational workflows."},
            {"number": "05", "title": "Launch", "description": "Deploy with team training, data migration, and ongoing operational support."},
            {"number": "06", "title": "Growth", "description": "Monitor usage, optimize workflows, add requested capabilities, and scale as needed."},
        ],
        "faqs": [
            {
                "q": "How do you scope custom software?",
                "a": "We run a collaborative discovery phase to map your processes, identify priorities, and define a precise delivery plan before development begins. This ensures alignment on scope and realistic expectations.",
            },
            {
                "q": "Can you work with our existing systems?",
                "a": "Yes. We regularly integrate with existing ERPs, CRMs, and internal tools via APIs and data pipelines. Legacy system integration is a standard part of our approach.",
            },
        ],
    },
    {
        "slug": "ui-ux-design",
        "name": "UI/UX Design",
        "tagline": "Interfaces people love to use",
        "short": "Research-driven product experiences designed for clarity, usability, and conversion.",
        "icon": "design",
        "features": [
            "Product strategy and research",
            "UX architecture and wireframes",
            "High-fidelity interface design",
            "Design systems",
            "Interactive prototypes",
            "Usability testing",
        ],
        "problems": [
            "Users struggling to complete key tasks",
            "High drop-off during important journeys",
            "Inconsistent product experiences",
            "Design decisions made without user insight",
        ],
        "tech": ["Figma", "Design Systems", "Prototyping", "User Research", "Usability Testing", "WCAG"],
        "benefits": [
            "Clearer user journeys",
            "Stronger product usability",
            "Consistent visual language",
            "Better collaboration between design and development",
        ],
        "use_cases": [
            "SaaS & web app UX redesigns",
            "Mobile app design systems",
            "Landing page & funnel design",
            "Enterprise internal tool interfaces",
        ],
        "process": [
            {"number": "01", "title": "Discovery", "description": "Understand your users, business objectives, competitive landscape, and current pain points."},
            {"number": "02", "title": "Strategy", "description": "Define the design approach, user flows, information architecture, and success metrics."},
            {"number": "03", "title": "Design", "description": "Create wireframes, prototypes, and high-fidelity designs based on user research insights."},
            {"number": "04", "title": "Development", "description": "Collaborate with engineering to translate designs into coded, interactive experiences."},
            {"number": "05", "title": "Launch", "description": "Deploy the redesigned product with monitoring for user engagement and feedback."},
            {"number": "06", "title": "Growth", "description": "Gather user feedback, iterate on design, optimize conversions, and expand capabilities."},
        ],
        "faqs": [
            {
                "q": "Do you design or build too?",
                "a": "We are a full-service studio — design and development teams work together throughout the project. This ensures the final product precisely matches the design vision and performs seamlessly.",
            },
            {
                "q": "How fast is a typical design engagement?",
                "a": "A focused design sprint can deliver prototypes in 2–4 weeks. Comprehensive design systems and full redesigns typically span 6–12 weeks depending on scope and discovery depth.",
            },
        ],
    },
    {
        "slug": "website-development",
        "name": "Website Development",
        "tagline": "Websites designed to convert and grow",
        "short": "Conversion-focused websites that communicate clearly, perform reliably, and support business growth.",
        "icon": "web",
        "features": [
            "Brand-forward website design",
            "Responsive layouts for all devices",
            "Content structure and user journeys",
            "SEO-ready architecture",
            "Lead capture and conversion pathways",
            "Performance and accessibility improvements",
        ],
        "problems": [
            "Web presence not reflecting the brand properly",
            "Low-quality leads from weak conversion paths",
            "Slow or outdated website experiences",
            "Difficulty updating content or campaigns quickly",
        ],
        "tech": ["Django", "Python", "HTML5", "CSS3", "JavaScript", "PostgreSQL"],
        "benefits": [
            "A stronger digital first impression",
            "Clearer communication of value and services",
            "Improved lead generation and inquiry quality",
            "A platform that is easier to update and grow",
        ],
        "use_cases": [
            "Corporate websites and company sites",
            "Marketing pages and lead-generation funnels",
            "Service business websites",
            "Portfolio and personal brand sites",
        ],
        "process": [
            {"number": "01", "title": "Discovery", "description": "Understand your audience, goals, messaging, and the content needed to convert visitors into leads."},
            {"number": "02", "title": "Strategy", "description": "Define the site structure, messaging hierarchy, user journeys, and technical requirements."},
            {"number": "03", "title": "Design", "description": "Sketch the layout, key sections, and user experience so the site feels clear and polished."},
            {"number": "04", "title": "Development", "description": "Build a responsive, maintainable site with strong performance, clean code, and structured content."},
            {"number": "05", "title": "Launch", "description": "Deploy the site with analytics, tracking, and checks to ensure a stable release."},
            {"number": "06", "title": "Growth", "description": "Measure engagement, improve pages, and iterate content as the business evolves."},
        ],
        "faqs": [
            {
                "q": "How long does a website project take?",
                "a": "Most focused website projects move in 3–8 weeks depending on scope, content readiness, and the number of pages or custom modules required.",
            },
            {
                "q": "Can you redesign an existing website?",
                "a": "Yes. We can modernize an existing web presence, improve messaging, and update the technical foundation without disrupting the business.",
            },
        ],
    },
    {
        "slug": "web-applications",
        "name": "Web Applications",
        "tagline": "Business workflows powered by software",
        "short": "Scalable web applications that streamline operations, improve visibility, and support internal or customer workflows.",
        "icon": "web",
        "features": [
            "Custom business applications",
            "Workflow automation",
            "Role-based dashboards and access",
            "Secure data management",
            "Reporting and analytics",
            "Integrations with existing systems",
        ],
        "problems": [
            "Business processes still rely on spreadsheets or disconnected tools",
            "Growing operations need better visibility and structure",
            "Manual workflows slow teams down",
            "Teams struggle to access accurate operational data",
        ],
        "tech": ["Django", "Python", "PostgreSQL", "Redis", "React", "REST APIs"],
        "benefits": [
            "Stronger process consistency",
            "Improved team productivity",
            "Centralized operational data",
            "Faster decisions backed by real-time information",
        ],
        "use_cases": [
            "Operations portals and internal systems",
            "Client-facing business apps",
            "Inventory, project, and approval platforms",
            "Workflow tracking dashboards",
        ],
        "process": [
            {"number": "01", "title": "Discovery", "description": "Map the workflows, systems, user roles, and operational requirements behind the application."},
            {"number": "02", "title": "Architecture", "description": "Define the application structure, data model, integrations, and implementation priorities."},
            {"number": "03", "title": "Design", "description": "Design key screens, workflows, and user interactions to support real business behavior."},
            {"number": "04", "title": "Development", "description": "Build the application, connect required systems, and validate business-critical flows."},
            {"number": "05", "title": "Launch", "description": "Deploy the application in a supported environment and check adoption and reliability."},
            {"number": "06", "title": "Optimization", "description": "Track usage, refine workflows, and add functionality as the business grows."},
        ],
        "faqs": [
            {
                "q": "What makes this different from a basic website?",
                "a": "Web applications support workflows, business logic, role-based access, integrations, and operational data management beyond simple content presentation.",
            },
            {
                "q": "Can the system integrate with existing tools?",
                "a": "Yes. We can connect applications to your current systems, APIs, and data sources to reduce friction and improve operational continuity.",
            },
        ],
    },
    {
        "slug": "custom-software",
        "name": "Custom Software",
        "tagline": "Purpose-built systems for complex operations",
        "short": "Tailored software solutions designed to fit your internal processes, integrations, and operational models.",
        "icon": "software",
        "features": [
            "Workflow automation",
            "Custom business logic",
            "Integrated APIs and data flows",
            "Operational dashboards",
            "Team-specific user experiences",
            "Scalable architecture for long-term use",
        ],
        "problems": [
            "Your process is too specialized for off-the-shelf tools",
            "Multiple teams rely on fragmented systems",
            "Manual coordination creates errors and delays",
            "Business rules change faster than your software can keep up",
        ],
        "tech": ["Python", "Django", "PostgreSQL", "Redis", "Docker", "REST APIs"],
        "benefits": [
            "Software tailored to your exact workflows",
            "Simplified operations and less manual work",
            "Better visibility across the organization",
            "Lower dependency on brittle spreadsheet processes",
        ],
        "use_cases": [
            "Operations and approval systems",
            "Internal business management tools",
            "Custom CRM or service workflows",
            "Legacy process modernization",
        ],
        "process": [
            {"number": "01", "title": "Discovery", "description": "Understand the process, constraints, user groups, and business rules behind the software need."},
            {"number": "02", "title": "Analysis", "description": "Document the requirements, define the data model, and identify high-value automation opportunities."},
            {"number": "03", "title": "Design", "description": "Map each workflow, interface, and decision path so the software matches the way teams work."},
            {"number": "04", "title": "Development", "description": "Build the application in iterative releases and validate each core workflow with real use cases."},
            {"number": "05", "title": "Launch", "description": "Deploy the system with onboarding, support, and operational monitoring."},
            {"number": "06", "title": "Iteration", "description": "Refine based on usage, expand capabilities, and improve long-term maintainability."},
        ],
        "faqs": [
            {
                "q": "When should a business choose custom software?",
                "a": "When your workflows, compliance needs, or operational model cannot be supported well by standard software without significant compromise.",
            },
            {
                "q": "Can you preserve existing tools and systems?",
                "a": "Yes. We can connect the custom system to legacy tools, spreadsheets, and third-party services in a way that reduces friction rather than replacing everything at once.",
            },
        ],
    },
    {
        "slug": "dashboard-development",
        "name": "Dashboard Development",
        "tagline": "Operational clarity at a glance",
        "short": "Actionable dashboards that help teams measure progress, identify issues, and act with confidence.",
        "icon": "software",
        "features": [
            "Executive KPI dashboards",
            "Operational monitoring views",
            "Data filtering and drill-down",
            "Custom charts and reports",
            "Real-time status tracking",
            "Role-based access and sharing",
        ],
        "problems": [
            "Teams lack visibility into performance and bottlenecks",
            "Reporting is spread across scattered spreadsheets and systems",
            "Decision-makers cannot find the right metrics quickly",
            "Operational issues are discovered too late",
        ],
        "tech": ["Python", "Django", "PostgreSQL", "Chart.js", "Power BI", "REST APIs"],
        "benefits": [
            "Faster decisions with better information",
            "Clearer operational visibility",
            "Improved team accountability",
            "Easier communication of performance and goals",
        ],
        "use_cases": [
            "Sales and marketing dashboards",
            "Operations and performance reporting",
            "Executive reporting centers",
            "Service performance and support tracking",
        ],
        "process": [
            {"number": "01", "title": "Discovery", "description": "Identify the KPIs, reports, and decisions that matter most to the users and stakeholders."},
            {"number": "02", "title": "Data Mapping", "description": "Review where the data lives and how it needs to be organized for clear reporting."},
            {"number": "03", "title": "Design", "description": "Design the dashboard layout, data storytelling, and interaction patterns for each user role."},
            {"number": "04", "title": "Development", "description": "Build the dashboard, validate the data flow, and refine the visual clarity of each view."},
            {"number": "05", "title": "Launch", "description": "Roll out the dashboard with stakeholder training and workflow checks."},
            {"number": "06", "title": "Iteration", "description": "Adjust dashboard views as teams' information needs evolve and new metrics become valuable."},
        ],
        "faqs": [
            {
                "q": "Can you connect existing data sources?",
                "a": "Yes. We regularly build dashboards from spreadsheets, internal systems, CRMs, and business databases to create a single source of operational truth.",
            },
            {
                "q": "Are dashboards only for executives?",
                "a": "No. Dashboards can be built for operations, customer support, sales, and delivery teams to support different decisions and improve accountability.",
            },
        ],
    },
    {
        "slug": "saas-development",
        "name": "SaaS Development",
        "tagline": "Scalable products built for growth",
        "short": "Product engineering for SaaS businesses that need strong foundations, onboarding, and long-term scalability.",
        "icon": "software",
        "features": [
            "Subscription product architecture",
            "User onboarding and accounts",
            "Billing and usage tracking",
            "Tenant or customer management",
            "Role-based permissions",
            "Analytics and product insights",
        ],
        "problems": [
            "Product growth is constrained by brittle systems or custom workarounds",
            "Customer onboarding is inconsistent across teams",
            "The product lacks the foundation for predictable scaling",
            "Teams need better data on product usage and retention",
        ],
        "tech": ["Python", "Django", "PostgreSQL", "Stripe", "Redis", "Docker"],
        "benefits": [
            "A product foundation that supports growth",
            "Stronger onboarding and customer experience",
            "More reliable operations as usage scales",
            "Better product visibility through usage analytics",
        ],
        "use_cases": [
            "B2B SaaS platforms",
            "Customer portals and dashboards",
            "Subscription management products",
            "Operational software delivered as a service",
        ],
        "process": [
            {"number": "01", "title": "Discovery", "description": "Clarify the product value proposition, user segments, early requirements, and commercial goals."},
            {"number": "02", "title": "Product Strategy", "description": "Prioritize MVP features, product architecture, and the roadmap for sustainable growth."},
            {"number": "03", "title": "Design", "description": "Design the customer journey, onboarding, and product flows that support retention."},
            {"number": "04", "title": "Development", "description": "Build the core product, subscriptions, dashboards, and integrations in measured stages."},
            {"number": "05", "title": "Launch", "description": "Deploy the product, validate customer flows, and establish monitoring and support."},
            {"number": "06", "title": "Scale", "description": "Measure usage, improve retention, and expand product capabilities as demand grows."},
        ],
        "faqs": [
            {
                "q": "Do you build product strategy as well as the software?",
                "a": "Yes. We can help clarify product scope, define priorities, and implement the product foundations needed for sustainable growth.",
            },
            {
                "q": "Can you support a SaaS launch from MVP to expansion?",
                "a": "Yes. We help build the first viable version and then extend functionality as product usage, customer needs, and operational complexity increase.",
            },
        ],
    },
    {
        "slug": "mobile-app-development",
        "name": "Mobile App Development",
        "tagline": "Better mobile experiences, built with purpose",
        "short": "Mobile applications designed around actual user needs, business workflows, and long-term product strategy.",
        "icon": "mobile",
        "features": [
            "iOS and Android products",
            "User onboarding and engagement flows",
            "API integrations and backend connectivity",
            "Push notifications and reminders",
            "Cross-platform or native build strategy",
            "App store launch support",
        ],
        "problems": [
            "Users do not have a mobile experience that matches the service or product",
            "Apps are difficult to maintain across versions and devices",
            "Teams cannot keep up with changing platform requirements",
            "Mobile features do not align with business goals or usage patterns",
        ],
        "tech": ["Flutter", "React Native", "Swift", "Kotlin", "Firebase", "REST APIs"],
        "benefits": [
            "A more usable mobile experience",
            "Better engagement and convenience for users",
            "Scalable product delivery across platforms",
            "A stable foundation for future mobile features",
        ],
        "use_cases": [
            "Field service apps",
            "Customer-facing mobile apps",
            "Internal productivity tools",
            "Mobile-first commerce or booking experiences",
        ],
        "process": [
            {"number": "01", "title": "Discovery", "description": "Understand the user personas, mobile goals, platform priorities, and business problem being solved."},
            {"number": "02", "title": "Strategy", "description": "Confirm the mobile approach, platform choice, feature scope, and timeline to support launch."},
            {"number": "03", "title": "Design", "description": "Design intuitive screens, interactions, and flows optimized for mobile behavior."},
            {"number": "04", "title": "Development", "description": "Build the app, validate device behavior, and connect the required backend services."},
            {"number": "05", "title": "Launch", "description": "Prepare store deployment, analytics, and release quality checks before release."},
            {"number": "06", "title": "Support", "description": "Monitor app health, improve performance, and iterate based on user and team feedback."},
        ],
        "faqs": [
            {
                "q": "Which platform should we choose first?",
                "a": "It depends on audience, user behavior, and business goals. We usually recommend the most cost-effective and defensible path while keeping future expansion in mind.",
            },
            {
                "q": "Can you maintain apps after launch?",
                "a": "Yes. We can support updates, bug fixes, feature improvements, and platform compatibility changes after the initial release.",
            },
        ],
    },
    {
        "slug": "ai-development",
        "name": "AI Development",
        "tagline": "Practical AI, designed for real business value",
        "short": "AI-powered systems built around useful workflows, trustworthy outputs, and measurable business impact.",
        "icon": "ai",
        "features": [
            "AI workflows and product features",
            "Prompt and logic design",
            "Intelligent automation",
            "Knowledge-grounded AI applications",
            "Human-in-the-loop controls",
            "Monitoring and quality improvement",
        ],
        "problems": [
            "Teams are exploring AI but need a clear, grounded use case",
            "AI demos do not translate into business workflows",
            "Data and workflows are too fragmented for effective automation",
            "Organizations need secure, practical AI systems instead of hype",
        ],
        "tech": ["Python", "OpenAI", "LangChain", "Pinecone", "PostgreSQL", "FastAPI"],
        "benefits": [
            "More efficient use of information and workflows",
            "Faster decision support and task assistance",
            "A more intelligent product or internal process",
            "A practical AI roadmap grounded in business needs",
        ],
        "use_cases": [
            "AI-powered support assistants",
            "Document processing and summarization",
            "Knowledge retrieval systems",
            "AI features inside internal tools and customer-facing products",
        ],
        "process": [
            {"number": "01", "title": "Discovery", "description": "Identify the most valuable AI opportunity, required data, user context, and constraints."},
            {"number": "02", "title": "Strategy", "description": "Define the architecture, risks, guardrails, and measurable success criteria for the solution."},
            {"number": "03", "title": "Design", "description": "Design prompts, workflows, trust points, and human review needs for the AI experience."},
            {"number": "04", "title": "Development", "description": "Build the solution, connect the knowledge and systems it needs, and validate quality."},
            {"number": "05", "title": "Launch", "description": "Deploy the system in a controlled environment and review output quality and adoption."},
            {"number": "06", "title": "Improve", "description": "Monitor real use, refine prompts and logic, and expand the system as the opportunity grows."},
        ],
        "faqs": [
            {
                "q": "Is AI only useful for large businesses?",
                "a": "No. Practical AI can add value to smaller businesses too, especially when connected to a clear workflow, a manageable data source, and a realistic operational goal.",
            },
            {
                "q": "How do we avoid unreliable AI output?",
                "a": "We design safeguards like grounded retrieval, validation steps, human review where needed, and clear operational boundaries so the system remains useful and trustworthy.",
            },
        ],
    },
    {
        "slug": "ai-assistants",
        "name": "AI Assistants",
        "tagline": "Intelligent help for work and customer experience",
        "short": "AI assistants that provide timely support, guidance, and structured information for teams and customers.",
        "icon": "ai",
        "features": [
            "Conversational assistants",
            "Knowledge-based responses",
            "Workflow help and task guidance",
            "Support ticket triage",
            "Internal team assistance",
            "Role-based access and context",
        ],
        "problems": [
            "Teams spend too much time answering repetitive questions",
            "Customers need faster support but resources are stretched",
            "Information is buried across tools and documents",
            "Users struggle to get the right guidance quickly",
        ],
        "tech": ["Python", "OpenAI", "Vector Search", "PostgreSQL", "FastAPI", "LangChain"],
        "benefits": [
            "Reduced repetitive support load",
            "Faster access to correct information",
            "Improved user experience and consistency",
            "A scalable front door for common questions and tasks",
        ],
        "use_cases": [
            "Customer support assistants",
            "Employee knowledge assistants",
            "Internal help and onboarding tools",
            "FAQ and service recommendation experiences",
        ],
        "process": [
            {"number": "01", "title": "Discovery", "description": "Identify the audience, questions, task flows, and boundaries for the assistant experience."},
            {"number": "02", "title": "Knowledge Setup", "description": "Gather and structure the knowledge sources the assistant needs to provide accurate and useful answers."},
            {"number": "03", "title": "Design", "description": "Design the conversation flow, safeguards, and escalation paths for human support when needed."},
            {"number": "04", "title": "Development", "description": "Build the assistant, integrate the data sources, and validate responses and user flows."},
            {"number": "05", "title": "Launch", "description": "Deploy the assistant with monitoring, feedback collection, and operational review."},
            {"number": "06", "title": "Improve", "description": "Refine prompts, knowledge coverage, and escalation decisions as real conversations emerge."},
        ],
        "faqs": [
            {
                "q": "Can the assistant be limited to approved information?",
                "a": "Yes. We can restrict answers to approved documentation, internal knowledge, and business rules, with escalation for issues that require a human decision.",
            },
            {
                "q": "Will it replace support teams?",
                "a": "No. The goal is to handle repetitive and informational interactions efficiently while allowing human teams to focus on complex or sensitive requests.",
            },
        ],
    },
    {
        "slug": "rag-solutions",
        "name": "RAG Solutions",
        "tagline": "Knowledge retrieval that improves decision quality",
        "short": "Retrieval-augmented generation systems that connect AI to your business documents, policies, and operational context.",
        "icon": "ai",
        "features": [
            "Document-aware AI answers",
            "Knowledge retrieval and summarization",
            "Structured source citations",
            "Business policy grounding",
            "Multi-document search and synthesis",
            "Version-aware knowledge access",
        ],
        "problems": [
            "Important knowledge is scattered across different systems and folders",
            "Users cannot find the right answer quickly",
            "AI outputs are too generic without business context",
            "Teams need a reliable way to access operational knowledge",
        ],
        "tech": ["Python", "OpenAI", "Vector Databases", "PostgreSQL", "LangChain", "FastAPI"],
        "benefits": [
            "More grounded and useful AI responses",
            "Faster access to institutional knowledge",
            "Better consistency across internal guidance and customer support",
            "A system tied to the business's real content and documents",
        ],
        "use_cases": [
            "Internal knowledge assistants",
            "Policy and procedure search",
            "Knowledge bases for customer or employee access",
            "AI-enhanced document and inquiry workflows",
        ],
        "process": [
            {"number": "01", "title": "Discovery", "description": "Identify the knowledge sources, user scenarios, and decision points where retrieval matters most."},
            {"number": "02", "title": "Content Mapping", "description": "Review and structure the documents, policies, and datasets the system should search and summarize."},
            {"number": "03", "title": "Design", "description": "Define retrieval logic, answer quality goals, and confidence or citation behavior."},
            {"number": "04", "title": "Development", "description": "Build the retrieval pipeline, vector search layer, and answer generation flow."},
            {"number": "05", "title": "Launch", "description": "Test retrieval quality in realistic scenarios and tune outputs before go-live."},
            {"number": "06", "title": "Improve", "description": "Add missing documents, tune retrieval quality, and expand the knowledge base as the system matures."},
        ],
        "faqs": [
            {
                "q": "Do we need a large dataset for RAG?",
                "a": "Not necessarily. Even smaller, curated knowledge bases often create the biggest operational benefit when the content is relevant and well-organized.",
            },
            {
                "q": "How do you keep answers accurate?",
                "a": "We ground the system in approved sources, review retrieval quality, and set clear boundaries around the use cases it can handle confidently.",
            },
        ],
    },
    {
        "slug": "api-development",
        "name": "API Development",
        "tagline": "Connected systems that work together",
        "short": "Secure APIs and integration layers that connect applications, services, and data sources into a cohesive system.",
        "icon": "software",
        "features": [
            "REST and GraphQL APIs",
            "Backend integration architecture",
            "Authentication and authorization",
            "Third-party service connectivity",
            "Data mapping and transformation",
            "API monitoring and documentation",
        ],
        "problems": [
            "Systems cannot communicate reliably",
            "Teams rely on manual data movement between tools",
            "Enterprise processes are blocked by disconnected backends",
            "Data updating across systems is inconsistent or slow",
        ],
        "tech": ["Python", "Django REST Framework", "PostgreSQL", "Redis", "JWT", "OpenAPI"],
        "benefits": [
            "Reliable connectivity between systems",
            "Better data flow and fewer manual steps",
            "Scalable back-end integrations",
            "Stronger reliability for business operations",
        ],
        "use_cases": [
            "Partner integrations",
            "Mobile and web app backends",
            "Internal system connectivity",
            "Data synchronization pipelines",
        ],
        "process": [
            {"number": "01", "title": "Discovery", "description": "Understand the integration needs, connected systems, and data contracts required for reliable operation."},
            {"number": "02", "title": "Design", "description": "Define the endpoints, auth model, error handling, and data flow architecture."},
            {"number": "03", "title": "Development", "description": "Build and validate the API layer with secure access, performance checks, and documentation."},
            {"number": "04", "title": "Testing", "description": "Exercise sample client flows, edge cases, and integration scenarios before deployment."},
            {"number": "05", "title": "Launch", "description": "Deploy the API with monitoring, versioning, and support for production use."},
            {"number": "06", "title": "Maintenance", "description": "Track reliability, update endpoints, and extend the API as systems evolve."},
        ],
        "faqs": [
            {
                "q": "Do you build custom APIs or integrate with existing ones?",
                "a": "Both. We can create new APIs for your product or connect to existing third-party services without introducing brittle point-to-point logic.",
            },
            {
                "q": "Can APIs support multiple clients?",
                "a": "Yes. APIs can be designed to support multiple internal tools, front-end clients, and partner systems while maintaining a clear contract and versioning plan.",
            },
        ],
    },
    {
        "slug": "maintenance-support",
        "name": "Maintenance & Support",
        "tagline": "Reliable systems deserve ongoing care",
        "short": "Ongoing maintenance, support, optimization, and technical guidance to keep systems healthy and useful over time.",
        "icon": "cloud",
        "features": [
            "Bug fixes and issue resolution",
            "Monitoring and health checks",
            "Security and dependency updates",
            "Performance optimization",
            "Feature enhancement support",
            "Technical guidance and roadmap support",
        ],
        "problems": [
            "Applications drift over time and become harder to maintain",
            "Teams lack a reliable partner for technical issues and updates",
            "System health degrades without ongoing monitoring and support",
            "There is no clear plan for iterative improvements and technical debt",
        ],
        "tech": ["Monitoring", "Security Updates", "Container Orchestration", "CI/CD", "Performance Testing", "Observability"],
        "benefits": [
            "Fewer unexpected issues and disruptions",
            "More consistent platform performance",
            "A healthy system that remains easier to evolve",
            "Ongoing technical support without relying on a single person or spreadsheet",
        ],
        "use_cases": [
            "Website and application maintenance",
            "Operational support for business systems",
            "Performance optimization and issue resolution",
            "Technical advisory and enhancement planning",
        ],
        "process": [
            {"number": "01", "title": "Review", "description": "Assess the current health, technical debt, and support needs of the platform or product."},
            {"number": "02", "title": "Prioritize", "description": "Identify the highest-impact fixes, updates, and improvements to support business continuity."},
            {"number": "03", "title": "Plan", "description": "Create a clear maintenance schedule, response rules, and release process."},
            {"number": "04", "title": "Operate", "description": "Monitor platforms, address issues, and support ongoing enhancement work."},
            {"number": "05", "title": "Improve", "description": "Refine performance, reduce friction, and keep the system aligned with business evolution."},
            {"number": "06", "title": "Support", "description": "Provide technical guidance and continuity as the business continues to grow and change."},
        ],
        "faqs": [
            {
                "q": "Do you offer ongoing support after launch?",
                "a": "Yes. We can provide maintenance plans covering issue handling, updates, monitoring, and ongoing improvements as your product or platform evolves.",
            },
            {
                "q": "How do you decide what to prioritize?",
                "a": "We focus first on reliability, business impact, and risk reduction, then move into improvements that increase value, usability, or operational efficiency.",
            },
        ],
    },
    {
        "slug": "erp",
        "name": "ERP — Enterprise Resource Planning",
        "tagline": "Connected operations for growing organizations",
        "short": "Centralize operations, automate workflows, connect departments, and improve visibility across your organization with a business-focused ERP system.",
        "icon": "erp",
        "features": [
            "Finance & Accounting",
            "Human Resources",
            "Payroll",
            "Inventory Management",
            "Procurement",
            "Sales Management",
            "Supply Chain Management",
            "Manufacturing Management",
            "CRM Integration",
            "Reporting & Analytics",
            "Workflow Automation",
            "Role-Based Access Control",
            "Business Intelligence",
            "Third-Party Integrations",
        ],
        "problems": [
            "Departments working from disconnected systems",
            "Manual processes slowing daily operations",
            "Limited visibility into business performance",
            "Inconsistent data and reporting across teams",
        ],
        "tech": ["Django", "Python", "PostgreSQL", "REST APIs", "Business Intelligence", "Workflow Automation"],
        "benefits": [
            "Centralized business operations",
            "Better data visibility",
            "Reduced manual processes",
            "Improved reporting",
            "Better departmental collaboration",
            "Workflow automation",
            "Scalable business operations",
            "Improved operational efficiency",
            "Better decision-making",
        ],
        "use_cases": [
            "Manufacturing",
            "Retail",
            "Healthcare",
            "Education",
            "Real Estate",
            "Logistics",
            "Professional Services",
            "Distribution",
            "Growing Enterprises",
        ],
        "process": [
            {"number": "01", "title": "Business Requirements", "description": "Understand the organization's goals, teams, processes, data, and ERP priorities."},
            {"number": "02", "title": "Process Analysis", "description": "Map current workflows and identify opportunities to improve coordination and automation."},
            {"number": "03", "title": "ERP Architecture", "description": "Define the system architecture, data model, integrations, and security foundation."},
            {"number": "04", "title": "Module Planning", "description": "Prioritize the ERP modules and delivery phases that create the most business value."},
            {"number": "05", "title": "Integration", "description": "Connect the ERP with existing systems, data sources, and third-party platforms."},
            {"number": "06", "title": "Development & Configuration", "description": "Configure and build the workflows, permissions, modules, and reporting experiences."},
            {"number": "07", "title": "Testing", "description": "Validate data, permissions, integrations, and end-to-end business processes."},
            {"number": "08", "title": "Deployment", "description": "Launch the ERP in a controlled rollout with migration and operational readiness checks."},
            {"number": "09", "title": "Training & Support", "description": "Help teams adopt the system and provide ongoing support as operations evolve."},
        ],
        "faqs": [
            {"q": "Can an ERP be introduced in phases?", "a": "Yes. We plan modules and releases around business priorities so teams can realize value progressively while keeping the architecture connected."},
            {"q": "Can an ERP integrate with existing tools?", "a": "Yes. We connect the ERP to existing systems and third-party services through documented, secure integrations."},
        ],
    },
    {
        "slug": "crm",
        "name": "CRM — Customer Relationship Management",
        "tagline": "Customer relationships, connected",
        "short": "Manage leads, customers, sales processes, communication, follow-ups, and customer relationships from one connected platform.",
        "icon": "crm",
        "features": [
            "Lead Management",
            "Contact Management",
            "Customer Management",
            "Sales Pipeline",
            "Opportunity Management",
            "Follow-Up Management",
            "Task & Activity Management",
            "Customer Communication",
            "Marketing Automation",
            "Customer Support",
            "Sales Automation",
            "Workflow Automation",
            "Reports & Analytics",
            "Customer Insights",
            "Third-Party Integrations",
        ],
        "problems": [
            "Leads and customer information spread across disconnected tools",
            "Follow-ups missed because sales activity is hard to track",
            "Teams lack a shared view of the sales pipeline",
            "Customer communication and reporting are difficult to coordinate",
        ],
        "tech": ["Django", "Python", "PostgreSQL", "REST APIs", "Workflow Automation", "Analytics"],
        "benefits": [
            "Better lead organization",
            "Improved sales visibility",
            "Faster follow-ups",
            "Centralized customer information",
            "Improved customer relationships",
            "Sales process automation",
            "Better team collaboration",
            "Improved conversion tracking",
            "Data-driven decision-making",
        ],
        "use_cases": [
            "Startups",
            "Small Businesses",
            "Enterprises",
            "Real Estate",
            "Healthcare",
            "Education",
            "Travel",
            "Professional Services",
            "E-commerce",
            "B2B Businesses",
        ],
        "process": [
            {"number": "01", "title": "Business Requirements", "description": "Understand the team's sales goals, customer data, communication needs, and reporting priorities."},
            {"number": "02", "title": "Customer Journey Analysis", "description": "Map how leads become customers and where better follow-up or visibility can improve the journey."},
            {"number": "03", "title": "CRM Architecture", "description": "Define the data model, user roles, integrations, and platform foundation."},
            {"number": "04", "title": "Pipeline & Workflow Design", "description": "Design pipelines, stages, activities, automations, and team workflows around the sales process."},
            {"number": "05", "title": "Integrations", "description": "Connect communication, marketing, support, finance, and other business systems."},
            {"number": "06", "title": "Development & Configuration", "description": "Configure and build the CRM experiences, automation, permissions, and reporting views."},
            {"number": "07", "title": "Testing", "description": "Validate customer data, pipeline behavior, automations, permissions, and integrations."},
            {"number": "08", "title": "Deployment", "description": "Roll out the CRM with data migration, access setup, and production readiness checks."},
            {"number": "09", "title": "Training & Support", "description": "Train teams, support adoption, and improve the CRM as customer operations evolve."},
        ],
        "faqs": [
            {"q": "Can the CRM support different sales teams?", "a": "Yes. We can tailor pipelines, permissions, activities, and reporting to different teams, regions, or customer segments."},
            {"q": "Can you migrate existing customer data?", "a": "Yes. We plan and validate data migration as part of implementation so teams can move into a consistent customer view."},
        ],
    },
]

INDUSTRIES = [
    {
        "slug": "real-estate",
        "name": "Real Estate",
        "tagline": "Digital platforms for property and growth",
        "short": "Custom technology platforms that centralize listings, streamline operations, and create seamless buyer and agent experiences.",
        "icon": "building",
        "challenges": [
            "Listing data fragmented across multiple channels and formats",
            "Manual lead follow-up and pipeline tracking",
            "Slow, outdated websites that lose buyers before inquiry",
            "Limited visibility into transaction pipeline and performance",
        ],
        "solutions": [
            "Unified property portals with smart search and filtering",
            "CRM and lead management systems built for real estate workflows",
            "High-performance websites optimized for buyer engagement",
            "Operational dashboards for agents, teams, and brokerages",
        ],
        "benefits": [
            "Centralized listing data across all channels",
            "Faster inquiry response and lead qualification",
            "Improved buyer experience and conversion rates",
            "Better transparency into pipeline and performance metrics",
        ],
        "relevant_services": ["Web Development", "Software Development", "UI/UX Design", "ERP — Enterprise Resource Planning", "CRM — Customer Relationship Management"],
        "use_cases": [
            "Property listing & discovery platforms",
            "Brokerage CRM & pipeline management",
            "Rental management and tenant portals",
            "Smart building & resident communication systems",
        ],
        "faqs": [
            {
                "q": "How do you handle real estate data integration?",
                "a": "We build systems that pull listing data from multiple sources (MLS, internal databases, APIs) and consolidate into a unified database. This ensures accurate, current information across all buyer-facing and internal channels.",
            },
            {
                "q": "Can you integrate with existing real estate tools?",
                "a": "Yes. We regularly integrate with CRMs, accounting systems, document management, and third-party services via APIs and data pipelines.",
            },
        ],
    },
    {
        "slug": "healthcare",
        "name": "Healthcare",
        "tagline": "Technology that cares",
        "short": "Secure, HIPAA-compliant digital health platforms that improve patient engagement, streamline clinical workflows, and enable better care coordination.",
        "icon": "health",
        "challenges": [
            "Strict compliance requirements (HIPAA, regulations) slowing innovation",
            "Outdated, fragmented patient management systems",
            "Limited tools for patient engagement and communication",
            "Clinical and administrative data trapped in separate systems",
        ],
        "solutions": [
            "HIPAA-compliant patient portals and engagement platforms",
            "Clinical workflow automation and task management",
            "Telehealth and secure appointment systems",
            "Secure data integration between clinical and administrative systems",
        ],
        "benefits": [
            "Regulatory compliance built into the platform foundation",
            "Reduced administrative burden on clinical staff",
            "Improved patient engagement and satisfaction",
            "Better care coordination through unified data",
        ],
        "relevant_services": ["Software Development", "AI & Automation", "ERP — Enterprise Resource Planning", "CRM — Customer Relationship Management", "UI/UX Design"],
        "use_cases": [
            "Patient scheduling & engagement portals",
            "Telemedicine platforms for remote consultations",
            "Electronic health record integrations and data sharing",
            "Clinical operations dashboards and reporting",
        ],
        "faqs": [
            {
                "q": "How do you ensure HIPAA compliance?",
                "a": "HIPAA compliance is built into our architecture from the start — encryption at rest and in transit, access controls, audit logs, and data retention policies. We work with your compliance team to ensure all requirements are met.",
            },
            {
                "q": "Can you integrate with existing EHR systems?",
                "a": "Yes. We build integrations with major EHR platforms (Epic, Cerner, athenahealth, etc.) via their APIs and HL7 standards for seamless data flow.",
            },
        ],
    },
    {
        "slug": "education",
        "name": "Education",
        "tagline": "Learning without limits",
        "short": "Comprehensive educational platforms that unify admissions, course delivery, assessments, and student communication in one experience.",
        "icon": "education",
        "challenges": [
            "Manual enrollment and admissions processes creating bottlenecks",
            "Difficulty engaging remote and hybrid learners",
            "Course delivery, scheduling, and coordination across multiple locations",
            "Student data scattered across spreadsheets and disconnected systems",
        ],
        "solutions": [
            "Unified learning management and student information systems",
            "Enrollment and admissions automation with workflow tools",
            "Interactive course delivery with assessments and progress tracking",
            "Student and faculty communication and collaboration platforms",
        ],
        "benefits": [
            "Streamlined enrollment without manual data entry",
            "Consistent, engaging learning experiences for all students",
            "Real-time visibility into student progress and outcomes",
            "Improved coordination between academic and administrative teams",
        ],
        "relevant_services": ["Web Development", "Software Development", "Mobile Development", "AI & Automation"],
        "use_cases": [
            "Learning management platforms (LMS) for institutions",
            "Student admission and enrollment systems",
            "Assessment, certification, and grade management tools",
            "Institutional dashboards for enrollment and outcomes analytics",
        ],
        "faqs": [
            {
                "q": "Do you support blended and remote learning?",
                "a": "Yes. Our platforms support traditional, blended, and fully remote learning with video integration, discussion forums, assignment submission, and progress tracking.",
            },
            {
                "q": "Can you integrate with student information systems?",
                "a": "Absolutely. We build integrations with existing SIS platforms and can migrate legacy data while maintaining historical records.",
            },
        ],
    },
    {
        "slug": "travel",
        "name": "Travel",
        "tagline": "Journeys deserve better technology",
        "short": "Booking platforms, operations tools, and customer experience systems built for travel companies, agencies, and tour operators.",
        "icon": "travel",
        "challenges": [
            "Complex inventory management across flights, hotels, activities, and packages",
            "Fragmented booking channels leading to double-bookings and errors",
            "Difficulty delivering personalized experiences at scale",
            "Thin margins demanding operational efficiency and cost control",
        ],
        "solutions": [
            "Custom booking and reservation platforms with real-time inventory",
            "Travel operations management systems for itinerary planning and fulfillment",
            "Dynamic pricing engines responsive to demand and market conditions",
            "Customer loyalty and engagement platforms with personalization",
        ],
        "benefits": [
            "Centralized inventory reduces double-bookings and errors",
            "Personalized recommendations increase conversion and customer lifetime value",
            "Operational automation reduces manual work and costs",
            "Real-time insights enable better pricing and promotions",
        ],
        "relevant_services": ["Web Development", "Software Development", "AI & Automation", "Mobile Development"],
        "use_cases": [
            "Hotel and resort booking platforms",
            "Tour operator management and itinerary systems",
            "Travel marketplace platforms connecting buyers and suppliers",
            "Customer loyalty and experience portals",
        ],
        "faqs": [
            {
                "q": "How do you handle real-time booking and inventory?",
                "a": "Our systems use real-time databases and caching to ensure inventory accuracy across channels. We integrate with supplier systems via APIs to keep data current.",
            },
            {
                "q": "Can you support multi-currency and multi-language booking?",
                "a": "Yes. Our platforms support global operations with multi-currency pricing, localized content, and payment methods appropriate to each market.",
            },
        ],
    },
    {
        "slug": "manufacturing",
        "name": "Manufacturing",
        "tagline": "Industry 4.0, operationalized",
        "short": "Smart manufacturing platforms combining IoT monitoring, predictive analytics, and operational dashboards for modern factories.",
        "icon": "manufacturing",
        "challenges": [
            "Limited real-time visibility into production line performance and quality",
            "Manual quality control and reporting creating delays and errors",
            "Reactive maintenance causing unplanned downtime and production losses",
            "Complex supply chain coordination across multiple suppliers and locations",
        ],
        "solutions": [
            "Production monitoring dashboards with real-time KPI tracking",
            "IoT sensor integration for equipment health and performance monitoring",
            "AI-powered predictive maintenance systems that forecast failures",
            "Supply chain management and vendor coordination systems",
        ],
        "benefits": [
            "Increased production uptime and reduced unplanned downtime",
            "Better quality control with real-time issue detection",
            "Improved supply chain efficiency and cost management",
            "Data-driven decision-making with production analytics",
        ],
        "relevant_services": ["Software Development", "AI & Automation", "ERP — Enterprise Resource Planning", "CRM — Customer Relationship Management", "Web Development"],
        "use_cases": [
            "Factory floor real-time analytics and KPI dashboards",
            "Equipment monitoring and predictive maintenance systems",
            "Quality management and inspection workflow automation",
            "Supply chain visibility and vendor management platforms",
        ],
        "faqs": [
            {
                "q": "What IoT sensors and devices do you support?",
                "a": "We integrate with industrial IoT platforms and can support sensors from major manufacturers. Our systems are sensor-agnostic and flexible for your existing hardware.",
            },
            {
                "q": "How does predictive maintenance work?",
                "a": "We analyze historical sensor data and equipment logs to identify failure patterns, then build models that predict failures with enough lead time for planned maintenance.",
            },
        ],
    },
    {
        "slug": "startups",
        "name": "Startups",
        "tagline": "From idea to launch, fast",
        "short": "End-to-end product development partners that help startups move from concept to market quickly and efficiently.",
        "icon": "startup",
        "challenges": [
            "Time pressure to build and launch MVP faster than competitors",
            "Limited budgets and engineering resources",
            "Uncertainty about product-market fit requiring rapid iteration",
            "Technical debt and scaling challenges after initial launch",
        ],
        "solutions": [
            "Rapid MVP development with focused scope and fast iteration cycles",
            "Product strategy and technical architecture guidance",
            "Full-stack development teams handling frontend, backend, and infrastructure",
            "Scalable architecture that grows with demand without major rewrites",
        ],
        "benefits": [
            "Faster time-to-market for MVP and subsequent releases",
            "Clear technical foundation that scales as the business grows",
            "Product strategy informed by market and user feedback",
            "Reduced technical debt and maintenance burden",
        ],
        "relevant_services": ["Web Development", "Mobile Development", "Software Development", "ERP — Enterprise Resource Planning", "CRM — Customer Relationship Management"],
        "use_cases": [
            "SaaS product MVPs and founder-validated concepts",
            "Marketplace platforms connecting buyers and sellers",
            "Mobile-first consumer apps",
            "Founder dashboards and investor reporting tools",
        ],
        "faqs": [
            {
                "q": "How fast can you build an MVP?",
                "a": "Timelines depend on scope and complexity. A focused, well-defined MVP can typically launch in 8–12 weeks. More complex platforms may require longer timelines.",
            },
            {
                "q": "How do you handle scaling after launch?",
                "a": "We build with scalability in mind from the start — cloud infrastructure, database design, and code architecture all account for growth. As demand increases, the system can scale without major rewrites.",
            },
        ],
    },
]

TECHNOLOGIES = [
    {
        "category": "Web & Application Development",
        "items": ["Python", "Django", "JavaScript", "HTML5", "CSS3", "REST APIs", "GraphQL"],
    },
    {
        "category": "AI & Machine Learning",
        "items": ["Python", "OpenAI", "PyTorch", "TensorFlow", "LangChain", "Pandas"],
    },
    {
        "category": "Mobile Development",
        "items": ["Flutter", "React Native", "Swift", "Kotlin", "Firebase"],
    },
    {
        "category": "Data & Databases",
        "items": ["PostgreSQL", "MySQL", "MongoDB", "Redis"],
    },
    {
        "category": "Cloud & Infrastructure",
        "items": ["AWS", "Google Cloud", "Microsoft Azure", "Cloudflare"],
    },
    {
        "category": "DevOps",
        "items": ["Docker", "Kubernetes", "Terraform", "GitHub Actions"],
    },
    {
        "category": "Product & Design",
        "items": ["Figma", "Design Systems", "Prototyping", "User Research", "Usability Testing", "WCAG"],
    },
]

class ProductStatus:
    """Product status constants for the showcase."""

    COMING_SOON = "coming_soon"
    IN_DEVELOPMENT = "in_development"
    BETA = "beta"
    LIVE = "live"
    ARCHIVED = "archived"

    LABELS = {
        COMING_SOON: "Coming Soon",
        IN_DEVELOPMENT: "In Development",
        BETA: "Beta",
        LIVE: "Live",
        ARCHIVED: "Archived",
    }

    # CTA label shown on product cards based on status.
    CTA_LABELS = {
        COMING_SOON: "Explore Product",
        IN_DEVELOPMENT: "View Progress",
        BETA: "Try Beta",
        LIVE: "Open Product",
        ARCHIVED: "Learn More",
    }


PRODUCTS = [
    {
        "slug": "ai-travel",
        "name": "AI Travel Platform",
        "short_name": "AI Travel",
        "tagline": "Smarter planning for modern travel",
        "description": "A travel planning experience designed to reduce decision fatigue and keep every trip more organised.",
        "long_description": (
            "AI Travel Platform is a planned product for travelers who move between "
            "inspiration sources, booking tools, and trip logistics. It brings "
            "discovery, planning, and day-of-travel support into one experience, "
            "with AI helping surface better decisions at the right moment."
        ),
        "category": "Travel Technology",
        "icon": "travel",
        "status": ProductStatus.COMING_SOON,
        "status_label": ProductStatus.LABELS[ProductStatus.COMING_SOON],
        "featured": True,
        "order": 1,
        "website_url": "",
        "internal_url": "/products/ai-travel/",
        "external_url": "",
        "cta_label": ProductStatus.CTA_LABELS[ProductStatus.COMING_SOON],
        "technologies": ["Python", "Django", "AI/ML", "Cloud"],
        "key_features": [
            "Trip discovery and inspiration",
            "Personalised itinerary planning",
            "Budget and travel coordination",
            "Smart recommendations and support",
        ],
        "vision": (
            "To help travelers move from inspiration to execution without losing the "
            "joy of discovery or the confidence of careful planning."
        ),
        "solves": (
            "Travelers often move between booking platforms, spreadsheets, and destination guides to plan a single trip. "
            "AI Travel Platform brings discovery, itinerary planning, and trip management into one more coherent experience."
        ),
        "status_note": (
            "This product is in planning and early development. Features shown are conceptual and may evolve as product requirements are refined."
        ),
    },
    {
        "slug": "society-management",
        "name": "Society Management Platform",
        "short_name": "Society Management",
        "tagline": "Clearer operations for residential communities",
        "description": "A resident-first operations platform for communities that need clearer communication and safer day-to-day processes.",
        "long_description": (
            "Society Management Platform is a planned system for residential communities "
            "that need smoother operations, stronger resident communication, and better "
            "visibility into day-to-day activity. It is designed to centralise resident "
            "requests, maintenance coordination, and security workflows in one place."
        ),
        "category": "Property Technology",
        "icon": "building",
        "status": ProductStatus.COMING_SOON,
        "status_label": ProductStatus.LABELS[ProductStatus.COMING_SOON],
        "featured": True,
        "order": 2,
        "website_url": "",
        "internal_url": "/products/society-management/",
        "external_url": "",
        "cta_label": ProductStatus.CTA_LABELS[ProductStatus.COMING_SOON],
        "technologies": ["Python", "Django", "PostgreSQL", "Mobile"],
        "key_features": [
            "Resident communication and updates",
            "Visitor and security tracking",
            "Maintenance and service requests",
            "Community operations dashboards",
        ],
        "vision": (
            "To help communities operate more transparently, efficiently, and confidently with digital workflows built around residents and staff."
        ),
        "solves": (
            "Housing societies often rely on fragmented communication and manual follow-ups across resident communication, maintenance requests, and security processes. "
            "This platform consolidates those workflows into a single system."
        ),
        "status_note": (
            "This product is in planning and early development. Functional scope and rollout priorities will be shaped by real community needs."
        ),
    },
    {
        "slug": "business-ai",
        "name": "Business AI Platform",
        "short_name": "Business AI",
        "tagline": "Practical AI for smarter business operations",
        "description": "A business intelligence platform that helps teams turn information into action with safer, more practical AI workflows.",
        "long_description": (
            "Business AI Platform is a planned product for organizations that need AI to be useful, governed and easy to trust. "
            "It is designed to connect knowledge, workflows, and decisions in a more structured way, helping teams work faster without sacrificing clarity or control."
        ),
        "category": "Artificial Intelligence",
        "icon": "ai",
        "status": ProductStatus.COMING_SOON,
        "status_label": ProductStatus.LABELS[ProductStatus.COMING_SOON],
        "featured": True,
        "order": 3,
        "website_url": "",
        "internal_url": "/products/business-ai/",
        "external_url": "",
        "cta_label": ProductStatus.CTA_LABELS[ProductStatus.COMING_SOON],
        "technologies": ["Python", "AI/ML", "LLM", "Cloud"],
        "key_features": [
            "Workflow automation and task support",
            "Knowledge retrieval and insight generation",
            "Decision support and reporting",
            "Governance and operational controls",
        ],
        "vision": (
            "To give organizations a safer foundation for operational AI — one that supports better decisions, faster execution, and clearer accountability."
        ),
        "solves": (
            "Many teams want to use AI but struggle with fragmented tools, unclear governance, and inconsistent results. "
            "Business AI Platform aims to make AI more practical and easier to govern and easy to trust across everyday business workflows."
        ),
        "status_note": (
            "This product is in planning and early development. Final capabilities will depend on workflow needs, governance requirements, and deployment scope."
        ),
    },
]

PORTFOLIO_ITEMS = [
    {
        "slug": "enterprise-operations-platform",
        "title": "Enterprise Operations Platform",
        "industry": "Enterprise",
        "services": ["Software Development", "ERP — Enterprise Resource Planning"],
        "tech": ["Python", "Django", "PostgreSQL"],
        "summary": "A unified operations platform that replaced fragmented spreadsheets and manual workflows.",
        "challenge": "A global enterprise relied on disconnected spreadsheets and manual handoffs, causing delays and data inconsistency across departments.",
        "strategy": "We mapped their end-to-end operations, then designed a unified platform with role-based dashboards and automated approval flows.",
        "solution": "A custom Django-based operations platform with modular dashboards, automated workflows, and a single source of truth for operational data.",
        "results": [
            "Centralized data across 6 departments",
            "Automated monthly reporting cycles",
            "Role-based secure access controls",
        ],
        "note": "Demo case study — client details intentionally generic.",
    },
    {
        "slug": "ai-document-processing",
        "title": "AI Document Processing",
        "industry": "Financial Services",
        "services": ["AI & Automation", "Software Development"],
        "tech": ["Python", "OpenAI", "PostgreSQL"],
        "summary": "An AI pipeline that automatically extracts, validates, and routes data from thousands of documents.",
        "challenge": "Hundreds of hours per month were spent manually keying data from invoices and contracts into core systems.",
        "strategy": "We combined OCR, NLP models, and validation rules to build a document intelligence pipeline that handles edge cases gracefully.",
        "solution": "A secure AI pipeline that ingests documents, extracts structured data, flags anomalies, and routes approved records to their target systems.",
        "results": [
            "~85% reduction in manual data entry",
            "Sub-second document processing times",
            "Human-in-the-loop review for edge cases",
        ],
        "note": "Demo case study — client details intentionally generic.",
    },
    {
        "slug": "premium-ecommerce-experience",
        "title": "Premium E-Commerce Experience",
        "industry": "E-Commerce",
        "services": ["Web Development", "UI/UX Design"],
        "tech": ["Django", "PostgreSQL", "JavaScript"],
        "summary": "A high-converting e-commerce platform with a premium brand experience.",
        "challenge": "An established retailer's store was slow, dated, and converting poorly on mobile — most visitors left before checkout.",
        "strategy": "We rebuilt the experience around a mobile-first design system with fast product discovery and a frictionless checkout.",
        "solution": "A blazing-fast, mobile-first e-commerce platform with a premium design system and streamlined checkout flow.",
        "results": [
            "Mobile conversion rate doubled post-launch",
            "Page load time reduced from 6s to under 2s",
            "Seamless inventory & order integration",
        ],
        "note": "Demo case study — client details intentionally generic.",
    },
    {
        "slug": "real-estate-portal",
        "title": "Real Estate Listing Portal",
        "industry": "Real Estate",
        "services": ["Web Development", "Software Development"],
        "tech": ["Django", "PostgreSQL", "Cloudflare"],
        "summary": "A property discovery platform connecting buyers with listings across a multi-city portfolio.",
        "challenge": "Listings were scattered across print, portals, and social media with no unified search experience for buyers.",
        "strategy": "We centralized listing data into a structured model and built an intuitive filtered search experience.",
        "solution": "A property portal with smart search, saved searches, and agent dashboard for managing listings.",
        "results": [
            "3x increase in qualified enquiries",
            "Centralized listing management",
            "Real-time listing availability",
        ],
        "note": "Demo case study — client details intentionally generic.",
    },
    {
        "slug": "education-management-system",
        "title": "Education Management System",
        "industry": "Education",
        "services": ["Software Development", "UI/UX Design"],
        "tech": ["Django", "PostgreSQL", "Redis"],
        "summary": "A complete platform managing admissions, courses, assessments, and student communication.",
        "challenge": "An institution juggled enrollment, course delivery, and reporting across disconnected tools and paper records.",
        "strategy": "We designed a role-based platform around the real workflows of students, faculty, and administrators.",
        "solution": "A unified education management system covering admissions, course scheduling, assessments, and communications.",
        "results": [
            "90% faster enrollment processing",
            "Unified student records",
            "Automated reporting for administrators",
        ],
        "note": "Demo case study — client details intentionally generic.",
    },
    {
        "slug": "predictive-maintenance",
        "title": "Predictive Maintenance System",
        "industry": "Manufacturing",
        "services": ["AI & Automation", "CRM — Customer Relationship Management"],
        "tech": ["Python", "TensorFlow", "AWS"],
        "summary": "An AI-driven system predicting equipment failures before they disrupt production.",
        "challenge": "Unplanned equipment downtime caused significant production losses across multiple factory lines.",
        "strategy": "We analyzed sensor telemetry to identify failure patterns and built a real-time prediction pipeline.",
        "solution": "A predictive maintenance platform ingesting sensor data, scoring failure risk, and triggering automated maintenance alerts.",
        "results": [
            "~30% reduction in unplanned downtime",
            "Real-time line health dashboard",
            "Automated alerting & work orders",
        ],
        "note": "Demo case study — client details intentionally generic.",
    },
]